### ISSUE TITLE
Update broke sensor detection.

### ISSUE THREAD

**Issue by iDumle** [Rem0o/FanControl.Releases#2465]
**Describe the bug**

Update V187 broke sensor detection for GPU Core for my AMD Radeon 6650 XT graphics card and it's now showing an incorrect/frozen value.
![Screenshot fancontrol setup2](https://github.com/Rem0o/FanControl.Releases/assets/141327899/56139bee-16cb-4c9a-bbad-30f8bfe5f834)

On version 186 the setup was working fine, and the software had no problem detecting the GPU Core sensor, I'm now using GPU Hot Spot instead as that seems to be updating its values.

Right after update the value was stuck at 468 'c, I then tried restarting twice after the update and the error persisted after reboot though GPU core showed a value of 0 'c and then subsequently 8 'c.

I have tried Refresh sensors detection, but it didn't change a thing it's still stuck on the same value.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
The Error log show no resent entry, though there is one from back in January I suspect it's unrelated, but just in case I'll post it.
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/15032917/log.txt)

**Relevant hardware specs and setup**
The graphics card is a ASUS Radeon RX 6650 XT DUAL OC - 8GB, and I am running window 10, and the newest graphics drivers 24.3.1.

And here is a picture of the whole Fan Control Setup.
![Screenshot fancontrol setup3](https://github.com/Rem0o/FanControl.Releases/assets/141327899/6e12b656-ae72-4fdc-99cf-c35d7bd649c2)

**Comment by BMKoot** [comment]
With my 7900XT, after update (187) for gpu sensors it only shows the VRSoC temp, where before it showed core and hot spot. Reverted (to 186) and it was fixed.

Windows 11, Powercolor Hellhound 7900XT, 24.3.1 drivers.

**Comment by seanbirkhead** [comment]
I lost all my custom fan names and paired sensors with update 187.
I restored 186 from a backup and all was fine again.
I think update 187 needs to be looked at.

**Comment by iDumle** [comment]
After digging around a bit, I saw your repo for LibreHardwareMonitor had a resent commit 2 days ago and you added that update to v187, I suspect something went wrong in the [d22cd1d](https://github.com/Rem0o/LibreHardwareMonitor/commit/d22cd1d9b34951ac3e172f6ff414e03ab9046856) commit.
So with that I tried swapping LibreHardwareMonitorLib.dll from v186 in to my v187 install and that restored the sensor functionality.

**Comment by Llamalland** [comment]
Similar issue, RX 6800, gpu core and liquid showing temps >3000°, gpu hot spot showing a sensible value. Happy to do more to diagnose/whatever, but for now I've just changed the sensor used to the hot spot.

**Comment by Rem0o** [comment]
Yeah there is a new method implemented to get sensor values, but there might be a bug in there.
[pmlog.zip](https://github.com/Rem0o/FanControl.Releases/files/15042413/pmlog.zip)

I compiled this: https://github.com/GPUOpen-LibrariesAndSDKs/display-library/blob/master/Sample/PMLog/PMLog.cpp

If anyone here is willing to run it and show the output, might be of some help.

**Comment by epinter** [comment]
I've compiled a test build of LibreHardwareMonitor with a possible fix for the issue. If the users with RX 6000 cards can test, will be useful.

[LibreHardwareMonitor-pmlogtest-b-20240419.zip](https://github.com/Rem0o/FanControl.Releases/files/15044056/LibreHardwareMonitor-pmlogtest-b-20240419.zip)

**Comment by iDumle** [comment]
> Yeah there is a new method implemented to get sensor values, but there might be a bug in there. [pmlog.zip](https://github.com/Rem0o/FanControl.Releases/files/15042413/pmlog.zip)
> 
> I compiled this: https://github.com/GPUOpen-LibrariesAndSDKs/display-library/blob/master/Sample/PMLog/PMLog.cpp
> 
> If anyone here is willing to run it and show the output, might be of some help.

@Rem0o 
I ran the pmlog file and no output was given to me, a terminal existed for maybe 0.2 sekunds but I am unable to catch if anything is written in it, so I'm not sure how I'm suppose to get an output for you.

> I've compiled a test build of LibreHardwareMonitor with a possible fix for the issue. If the users with RX 6000 cards can test, will be useful (LibreHardwareMonitorLib.dll included in zip). The temps should be shown correctly with this build. A test copying the new LibreHardwareMonitorLib to fancontrol would be useful too.
> 
> [LibreHardwareMonitor-pmlogtest-b-20240419.zip](https://github.com/Rem0o/FanControl.Releases/files/15044056/LibreHardwareMonitor-pmlogtest-b-20240419.zip)

@epinter
I ran the Libre hardware monitor and all the sensor seems to be working correctly, I opened a game and the temp in LHM corresponded to the temp show by the in game monitor.
![LibHwMonOutput](https://github.com/Rem0o/FanControl.Releases/assets/141327899/f219f0e4-f427-4fc4-b967-a2f8ed6a3e93)

I swapped the LibreHardwareMonitorLib.dll file from LHM to Fan Control v187 folder and ran the software again, and it seems to be working fine now.
![FanControlSensorMenu](https://github.com/Rem0o/FanControl.Releases/assets/141327899/4b34d3bc-2f03-4e02-95cf-b7eea2087650)

**Comment by epinter** [comment]
@iDumle
The pmlog sample @Rem0o sent is an official sample from AMD that uses that feature pmlog to collect sensors. To run it, you can use these parameters: pmlog.exe s 0 1000 1000.

Anyway, if the test build shows the values correctly, some boards of RX 6000 series doesn't work with pmlog feature. I will send a PR to LibreHardwareMonitor excluding these boards and use the old method.  It's weird that pmlog worked for me with a RX 6750 XT.

**Comment by iDumle** [comment]
I ran pmlog again with the parameters you gave me and was able to see the output.
![PMlogOutput](https://github.com/Rem0o/FanControl.Releases/assets/141327899/3e09601d-a417-43f5-90f8-8cfff75c12f6)

I hope it all helps, and your welcome I am glad I can be helpful, It's a fantastic software you guys are building, so just happy to be of aid.

**Comment by iDumle** [comment]
I noticed that pmlog is detecting an edge temp sensor so I ran it in the background while running overwatch and pmlog is updating then temp correctly and it matches with the temp sensor in overwatch.
![PmlogEdgeTempWorking](https://github.com/Rem0o/FanControl.Releases/assets/141327899/a34b423c-58ee-4f92-9d07-b75766c0ea07)

This should be the same sensor that v187 LibreHardwareMonitorLib.dll was trying to monitor with the new method right?
Not sure what's going on but I though i'd mention it.

**Comment by epinter** [comment]
> I noticed that pmlog is detecting an edge temp sensor so I ran it in the background while running overwatch and pmlog is updating the temp correctly and it matches with the temp sensor in overwatch. ![PmlogEdgeTempWorking](https://private-user-images.githubusercontent.com/141327899/324130611-a34b423c-58ee-4f92-9d07-b75766c0ea07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NjY1OTYsIm5iZiI6MTcxMzU2NjI5NiwicGF0aCI6Ii8xNDEzMjc4OTkvMzI0MTMwNjExLWEzNGI0MjNjLTU4ZWUtNGY5Mi05ZDA3LWI3NTc2NmMwZWEwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQyMjM4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDk3MWVmMmQwNzYyYThkOWMzZWFhMTRmMGMxZWI5Nzc0MzhmMGNkNWVkZmE5NzIyYjdmY2ZjNzllMjYxN2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QKiE5nNNyepvOKi7EZTNN19Gzup1cqv8ssB9b1qX1CQ)
> 
> This should be the same sensor that v187 LibreHardwareMonitorLib.dll was trying to monitor with the new method right? Not sure what's going on but I though i'd mention it.

That's weird. Something is breaking the pmlog inside the librehardwaremonitor and not in this sample. I think it's better to make RX 6000 to use old method to collect sensors.

**Comment by iDumle** [comment]
> That's weird. Something is breaking the pmlog inside the librehardwaremonitor and not in this sample. I think it's better to make RX 6000 to use old method to collect sensors.

The saying "If it ain't broken, don't fixet" comes to mind :) that said if you at some point decide to give the new method a once over again I'd be happy to test it out.

**Comment by axel-lebourhis** [comment]
I'm having the same kind of issue with my 7800 XT, sensors value are corrupted, so fancontrol looses its mind and ramps the fans all the way up. Went back to 186 and no more issue.

**Comment by epinter** [comment]
> I'm having the same kind of issue with my 7800 XT, sensors value are corrupted, so fancontrol looses its mind and ramps the fans all the way up. Went back to 186 and no more issue.

7800 XT doesn't have problems with the build LibreHardwareMonitor fancontrol 187 is based, actually the sensors of 7800 was fixed by newer lhm build.

**Comment by epinter** [comment]
@iDumle 
Can you test this LHM build ? It's unchanged, using the new method to get the sensors. Just to be sure.

[LibreHardwareMonitor-net472-nightly-4d6a755c.zip](https://github.com/Rem0o/FanControl.Releases/files/15052825/LibreHardwareMonitor-net472-nightly-4d6a755c.zip)

**Comment by iDumle** [comment]
@epinter 
So I just ran LHM in the background while running overwatch, and as far as I can see the sensors are working fine and lines up with the one in overwatch and amd adrenalin.
![LibHwMonOutput187base](https://github.com/Rem0o/FanControl.Releases/assets/141327899/f20f2c2c-9b17-4394-ae6c-1e002404280c)

So something seems to gets missaligned from LHM to Fan Control.

**Comment by epinter** [comment]
> @epinter So I just ran LHM in the background while running overwatch, and as far as I can see the sensors are working fine and lines up with the one in overwatch and amd adrenalin. ![LibHwMonOutput187base](https://private-user-images.githubusercontent.com/141327899/324266913-f20f2c2c-9b17-4394-ae6c-1e002404280c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MjE0MDgsIm5iZiI6MTcxMzcyMTEwOCwicGF0aCI6Ii8xNDEzMjc4OTkvMzI0MjY2OTEzLWYyMGYyYzJjLTliMTctNDM5NC1hZTZjLTFlMDAyNDA0MjgwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxNzM4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWM5OTUwMmYzZGFjMDM2YzgwYzg5OGUyMzRmNzM3MzIwM2FhMGYzOTIxYjhlNTFkOTA1MDZkOThmYTJiM2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4M2P2zY1Ihy-3apV2xohH3up0zczOgH3XnvIYYHOJD0)
> 
> So something seems to gets missaligned from LHM to Fan Control.

Thanks for the test! So LHM is working.

**Comment by epinter** [comment]
@Rem0o LHM is working with 6650 too, like in my test with 6750. Any idea what can cause the problem ? Maybe an issue with [this](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/331d334aef6939482ae0b5491865311b87de17ba/LibreHardwareMonitorLib/Hardware/Gpu/AmdGpu.cs#L572) ?

**Comment by iDumle** [comment]
Okay I properly should have done this from the start(feeling a little dumb I didn't do this to begin with), given the new test I did, I tried a complete redownload of v187 and imported my old config, and It seems to working as it should, so now I'm thinking something went wrong with auto updating from v186 to v187 rather then v187 not working.
![CleanInstallOf187](https://github.com/Rem0o/FanControl.Releases/assets/141327899/f6a08a2c-1208-493c-b95e-449b641b8594)

**Comment by Rem0o** [comment]
The downloadable LHM is not the most up to date version. I'm using the latest commit since I'm compiling it myself. 
@iDumle

**Comment by epinter** [comment]
@Rem0o The build I told @iDumle to download (LibreHardwareMonitor-net472-nightly-4d6a755c.zip) is using the latest [commit](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/4d6a755c115b8dc497166088f2fe6db6206f6323).

**Comment by iDumle** [comment]
I'll try and make a detailed timeline of my use of the software, maybe it can shine some light on something.

- I first downloaded FanControl after seeing Jays2cent featuring it, this was done on 14/02-2023 03:58 and was version v146
- I unpacked it to its own folder inside my download folder, and it has not been moved afterwards.
- I have since not interacted with the GitHub repo up until now and all subsequent updates has happened inside the software it self when prompted.
- All updates have been without a problem, until the update from v186 to v187, immediately after the update I noted the odd behaviour, did the restarts and documented the behaviour and created this issue.
- Everything else is laid out in this post.

What the actual root course for the odd behaviour I experienced is, I can only speculated on, It could be a windows thing, or maybe related to the fact my first version was v146 and all updated was done in software and never redownloaded from repo, or it might be that I was just unlucky.

What I do know is that I have done a new install from a newly download zip of v187 from the Github repo and unpacked it to its own folder on my desktop and loaded up my old config file, and it's working fine.

I don't know if this is helpful at all but now you have it.

**Comment by axel-lebourhis** [comment]
> > I'm having the same kind of issue with my 7800 XT, sensors value are corrupted, so fancontrol looses its mind and ramps the fans all the way up. Went back to 186 and no more issue.
> 
> 7800 XT doesn't have problems with the build LibreHardwareMonitor fancontrol 187 is based, actually the sensors of 7800 was fixed by that build. Try the build I posted above.

I tested the build you posted, here is the result:
![image](https://github.com/Rem0o/FanControl.Releases/assets/24732621/cfcca4d3-7dd2-4149-986d-56ae3ed513b2)

In FanControl:
![image](https://github.com/Rem0o/FanControl.Releases/assets/24732621/5a50b8d9-df45-4416-8389-f2f93d703eca)

**Comment by epinter** [comment]
I don't understand...


![rx6750xt-4d6a755c](https://github.com/Rem0o/FanControl.Releases/assets/1561280/2dd56f5d-1b99-418c-8ab4-34b9ff3f31b6)

![rx7800xt-4d6a755c](https://github.com/Rem0o/FanControl.Releases/assets/1561280/ddc965a0-1856-4bc1-96ec-a88b28354794)

**Comment by epinter** [comment]
@axel-lebourhis When you have time, can you try to run and tell me what happens ? I'm trying to isolate some code path.

[LibreHardwareMonitor-net472-test1-nooverdrive-20240422.zip](https://github.com/Rem0o/FanControl.Releases/files/15069585/LibreHardwareMonitor-net472-test1-nooverdrive-20240422.zip)

**Comment by epinter** [comment]
@iDumle 

Can you try this ?
[LibreHardwareMonitor-test2-refactor-getsensor.zip](https://github.com/Rem0o/FanControl.Releases/files/15079035/LibreHardwareMonitor-test2-refactor-getsensor.zip)

**Comment by epinter** [comment]
@iDumle 

Can you try this ?

[LibreHardwareMonitor-test2-getsensor_factor-20240423.zip](https://github.com/Rem0o/FanControl.Releases/files/15079114/LibreHardwareMonitor-test2-getsensor_factor-20240423.zip)

**Comment by iDumle** [comment]
@epinter I tested the LHM and I have two results for you.

This one I did right after downloading your LHM, and it's clearly broken, the computer had been running for about 2 hours.
![LHM-test2-getsensor_factor-20240423](https://github.com/Rem0o/FanControl.Releases/assets/141327899/1f743faa-a69a-47c6-9c12-e543d2c68727)

I then did a reboot and had LHM boot with window, and I got a different result, ran overwatch and it responded fine.
![LHM-test2-getsensor_factor-20240423-TestAfterBoot-StartWithWindows](https://github.com/Rem0o/FanControl.Releases/assets/141327899/361af58a-8177-4354-b5d5-98bc4cbda332)

I then did a third reboot with start with windows disabled and it mirrored the 2nd test and was working fine too (I didn't screenshot it).

I hope this is informative enough, please tell me if you want additional data.

**Comment by epinter** [comment]
Do you have Valorant anticheat or any other similar anticheat running ? If so try to close them next time LHM presents weird data, and restart LHM.

**Comment by iDumle** [comment]
I do have vanguard from Valorant installed, and game guard I think it's called from Helldivers 2, but I think vanguard is the only one that starts with windows, It's hard to avoid root level anti-cheat in todays gaming.
But I'll keep and eye out for when it acts up again and try out the tests, though it's a little sporadic it seems.

**Comment by iDumle** [comment]
@epinter 
Took some time, but now I got the opportunity to test it out.
After a coldboot my fancontrol broke the sensor, so I ran the LHM you gave me, and it's also broken.
![LHM-test2-getsensor_factor-20240423-27-04-2024-Coldboot-BeforeVanguadShutDown2](https://github.com/Rem0o/FanControl.Releases/assets/141327899/2c51839b-3969-4a03-b990-3f457483e8bd)
FanContol v187 look like this.
![FanControlSensorMenu-27-04-2024](https://github.com/Rem0o/FanControl.Releases/assets/141327899/0db8a9ae-e891-46d3-9f9d-a60fcc6a3104)

I then closed down LHM, Fancontol, and shutdown vanguard, and ran LHM again but the result stayed the same.
![LHM-test2-getsensor_factor-20240423-27-04-2024-Coldboot-AfterVanguadShutDown](https://github.com/Rem0o/FanControl.Releases/assets/141327899/abcdd138-b00b-486d-a784-b711de86a5ae)

As I'm not playing valorant really atm I could try and uninstall it and vanguard completely if you think that could be of any help.
Though ideally they and fancontrol should be able to coexist.

**Comment by epinter** [comment]
> @epinter Took some time, but now I got the opportunity to test it out. After a coldboot my fancontrol broke the sensor, so I ran the LHM you gave me, and it's also broken. ![LHM-test2-getsensor_factor-20240423-27-04-2024-Coldboot-BeforeVanguadShutDown2](https://private-user-images.githubusercontent.com/141327899/326154214-2c51839b-3969-4a03-b990-3f457483e8bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTUwNzksIm5iZiI6MTcxNDE5NDc3OSwicGF0aCI6Ii8xNDEzMjc4OTkvMzI2MTU0MjE0LTJjNTE4MzliLTM5NjktNGEwMy1iOTkwLTNmNDU3NDgzZThiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwNTEyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjJmYjU1OTk5Y2RhOWY2OThlMzI0ZWQyOTQ4N2ZmN2U5Y2M0NzdjMWZmYWQ2ZWU4NWE2NGFjYWI1ZTBhYjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YMqb_GezjlPyJ8yjh_ZWZf63Kuy5APLFYHlB-QfhNSo) FanContol v187 look like this. ![FanControlSensorMenu-27-04-2024](https://private-user-images.githubusercontent.com/141327899/326154254-0db8a9ae-e891-46d3-9f9d-a60fcc6a3104.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTUwNzksIm5iZiI6MTcxNDE5NDc3OSwicGF0aCI6Ii8xNDEzMjc4OTkvMzI2MTU0MjU0LTBkYjhhOWFlLWU4OTEtNDZkMy05ZjlkLWE2MGZjYzZhMzEwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwNTEyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjQ2ZjBiYTJhMzk5ZDFlYjI5ZTA2YTEyZjlhZWNjZWFlZTNhNDY3ODBhOGVlMTNiNjVkMzkwYjFkNmU4ZGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fBK_LxrMeeT5EC-uel9n5n6TfV0uHhi7vI2WL9BSquk)
> 
> I then closed down LHM, Fancontol, and shutdown vanguard, and ran LHM again but the result stayed the same. ![LHM-test2-getsensor_factor-20240423-27-04-2024-Coldboot-AfterVanguadShutDown](https://private-user-images.githubusercontent.com/141327899/326154316-abcdd138-b00b-486d-a784-b711de86a5ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTUwNzksIm5iZiI6MTcxNDE5NDc3OSwicGF0aCI6Ii8xNDEzMjc4OTkvMzI2MTU0MzE2LWFiY2RkMTM4LWIwMGItNDg2ZC1hNzg0LWI3MTFkZTg2YTVhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwNTEyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTZiM2Q4YTg1MmM2YzUyNjY0NTliMjA0MGIxYThlMjEwZmE0ZWZlZDMxZWU3Zjc4MGIzNWMxNDVmM2Q1YjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cJzY8HZabfBWqw6BkNWFlStSm8XIk42Xo1HQvtvy3t4)
> 
> As I'm not playing valorant really atm I could try and uninstall it and vanguard completely if you think that could be of any help. Though ideally they and fancontrol should be able to coexist.

Vanguard is not the only the breaks monitoring tools. Today while testing stable builds of LHM (0.9.2 and 0.9.3), I saw EA FC 2024 breaking all CPU sensors, as soon as the game was closed, all sensors worked again. Didn't affect the gpu sensors in this case.

**Comment by iDumle** [comment]
From what I've observed, Vanguard seems to be the only one that actively run at system boot, other root-level anti cheat seems to only become active when the application is running, for example nProtect starts with the launch of Helldivers 2.

But another thing I've noticed is, sometime when Fancontrol has broken it has added these "Phantom" sensors in the menu, as shown by "GPU VR VDDC" a sensor being present in the picture I took today, a sensor not present in the Pmlog from what I can see. 5 days ago it added 3 "Phantom" sensors. Could be an issue with how LHM detects sensors?

**Comment by epinter** [comment]
LHM expects amd driver to deliver the sensors data correctly, if something blocks or intercepts that access to the sensor data provided by the driver, LHM can present invalid data, like a sensor that doesn't have data to return something, or a valid sensor returning wrong data. I use LHM sensors all the time, I keep them open in my second display, I have zero problems with sensors on amd cards. I tested the last builds in 2 different PCs two different amd cards, no issues.

**Comment by iDumle** [comment]
@epinter 
You said something could block or intercept the sensor data, so I spend the morning testing out a dual boot window I have on this PC, it was a system meant to be a work system I just never got around to really setting up, this setup is as clean as it gets on my PC, without me completely reformatting it everything.
It's Windows 10, AMD Graphics Driver, Logitech G Hub, and Audacity, this is all that has been installed to it besides windows updates.

I spend some time restarting and opening LHM over and over, while most of the time it was only "Phantom" Sensors popping in and out of the nightly build, the temps was still updating, but on the 5 restart I got a 0 temp sensor.
Here is a screenshot of the getsensor version you gave me.
![LHMgetsensor-SomethingStillWonkyEvenOnCleanWindows](https://github.com/Rem0o/FanControl.Releases/assets/141327899/680c45c2-3d46-49bb-af7e-88a65d69bad5)

And this is of the nightly version of LHM
![LHMnightly-SomethingStillWonkyEvenOnCleanWindows](https://github.com/Rem0o/FanControl.Releases/assets/141327899/3743a07a-7eef-4b0d-a83e-3e9846f90d6b)

I think this is properly as clean of a test setup I can give of my PC, only thing I can't test is window 10 it self as my system can't run window 11.

**Comment by GEKonPC** [comment]
![g2aqIYN2RO](https://github.com/Rem0o/FanControl.Releases/assets/162819753/d30a1b29-30cf-4b67-a186-d1484ea0d60b)
i have the same problem with 5700xt, it is very random.. only the hotspot is updating (out of the gpu sensors)

**Comment by epinter** [comment]
> @epinter You said something could block or intercept the sensor data, so I spend the morning testing out a dual boot window I have on this PC, it was a system meant to be a work system I just never got around to really setting up, this setup is as clean as it gets on my PC, without me completely reformatting everything. It's Windows 10, AMD Graphics Driver, Logitech G Hub, and Audacity, this is all that has been installed to it besides windows updates.
> 
> I spend some time restarting and opening LHM over and over, while most of the time it was only "Phantom" Sensors popping in and out of the nightly build, the temps was still updating, but on the 5 restart I got a 0 temp sensor. Here is a screenshot of the getsensor version you gave me. 
> 
> And this is of the nightly version of LHM 
> 
> I think this is properly as clean of a test setup I can give of my PC, only thing I can't test is window 10 it self as my system can't run window 11.

Good tests, thank you. That sensors that doesn't exists can be a missing support check in that nightly build, I implemented a check 
for supported sensors in a new commit. The sensor with temp 0 is hard to tell, but could be something that failed to initialize when launching LHM.

A new commit was merged, I think the newer builds of LHM should help with these problems. LHM will try to detect problems with sensor data and try to get using old method if it's the case. You can download it here: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/8859565890. Get the LibreHardwareMonitor-net472.

**Comment by iDumle** [comment]
@epinter
I just had a cold boot on my normal system and was meet with a broken core sensor on the new LHM build you gave me.
![LHM-29-04-2024-Coldboot](https://github.com/Rem0o/FanControl.Releases/assets/141327899/23491bb0-50c7-48ca-9c2f-b4fc7618a04b)
I used the new LHM dll in fancontrol, to more easily spot when the sensor goes crazy, and this is what it looks like.
![FanControlSensorMenu 29-04-2024](https://github.com/Rem0o/FanControl.Releases/assets/141327899/64b69397-96c9-4dcd-8854-8867cac04784)

What I find puzzling is that no matter how many time I close and open the app, it's always the same broken number on the same boot, same goes for if I open the nightly build or the getsonsor version of LHM. You'd think it would try and pull new data when you open the app again, I find it weird that it just breaks/freezes on boot and then never get unstuck unless you restart.

**Comment by epinter** [comment]
This is weird. In the new commit that was merged, I added a check to verify that the sensor is supported and use old method if not ([here](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/0c3ebb1933d10bf274715302a7cdac971e80a0ba/LibreHardwareMonitorLib/Hardware/Gpu/AmdGpu.cs#L463)), and also added a check to validate that the sensor data that came from the amd library is valid ([here](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/0c3ebb1933d10bf274715302a7cdac971e80a0ba/LibreHardwareMonitorLib/Hardware/Gpu/AmdGpu.cs#L452)). If the structure is corrupted, the old method will be used, but doesn 't seems to be the case. Have you tried to save the report on LHM and see the sensors there ?

**Comment by Rem0o** [comment]
@epinter  I followed this thread along, and was wondering is PMLog is the way forward for sensors with newer AMD gpus.  From the what I can understand in the doc it was developped for Wattman as an Overdrive 8 binding. I believe these were discontinued/phased out?  I have been developping [this](https://github.com/Rem0o/FanControl.ADLX) lately which uses ALDX, the newest SDK, used by Adrenaline.  Was wondering if that would be a better way forward for LHM.

**Comment by epinter** [comment]
> @epinter I followed this thread along, and was wondering is PMLog is the way forward for sensors with newer AMD gpus. From the what I can understand in the doc it was developped for Wattman as an Overdrive 8 binding. I believe these were discontinued/phased out? I have been developping [this](https://github.com/Rem0o/FanControl.ADLX) lately which uses ALDX, the newest SDK, used by Adrenaline. Was wondering if that would be a better way forward for LHM.

I took a look at ADLX doc recently. I think would be much better to use it for newer gpus, but by the doc, it requires Windows 10, and it's not clear what gpus are supported. I don't know the direction LHM author wants, if a Windows 10 only would be ok... I hoped a conditional PMlog and OD8 would be sufficient, and it was for the tests I made, but this case of @iDumle is weird. All tests I made worked with my amd gpus. I still have my doubts if ADLX inside LHM would work flawless.

**Comment by Rem0o** [comment]
@epinter  if you are curious, built some c# bindings here and got a test console project to test stuff: https://github.com/Rem0o/ADLX/tree/main/Samples/csharp/ADLXWrapper.TestConsole

**Comment by epinter** [comment]
> @epinter if you are curious, built some c# bindings here and got a test console project to test stuff: https://github.com/Rem0o/ADLX/tree/main/Samples/csharp/ADLXWrapper.TestConsole

I will take a look

**Comment by epinter** [comment]
I found an interesting problem in LHM. In my case the class that handles the amd gpu sensors was initialized 5 times, LHM was finding and trying to use 4 inactive devices. Not sure if it might be related to this issue, but here it is:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1324/commits/654c89df0f0f4b53c7dba40d4a22d2d1ba8ee969

[Build](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/8887812096/artifacts/1458833810)

**Comment by epinter** [comment]
I'm still working on it, but if you want to test this new build, I'm changing some things in the initialization of sensors...

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/8890213800

**Comment by GEKonPC** [comment]
V188 seems to have fixed the issue so far

**Comment by iDumle** [comment]
Just updated to v188 and upon update the sensors are working fine, and only the core and hot spot sensors are present in the menu, hopefully this means it's fixed, but I will respond back if something comes up.

**Comment by acegrm** [comment]
Greetings, just here to say I too have been having these issues since v187, im using a 7800xt,
since then I had temporarily switched my primary curve control to the CPU sensor (im only controlling case fans with FanControl).
I just updated to v188 and after a couple reboots the GPU sensors and the app in general seem to be working properly.

**Comment by GEKonPC** [comment]
> V188 seems to have fixed the issue so far

nevermind seems to be still broken, my pc did crash though so that might be a factor
![image](https://github.com/Rem0o/FanControl.Releases/assets/162819753/b849a023-6e59-4152-b8fd-f2e2e61b95ef)

**Comment by epinter** [comment]
@iDumle I know you must be tired of all the tests you made :), I thank you really, unfortunatelly I don't see other developer working on the amd sensors on LHM, and I'm unable to reproduce... I really want to solve this thing, at least find the real cause. If you have a time, when you see your fans completely crazy try to run LHM and save the report (in the file menu).

**Comment by epinter** [comment]
New build available:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/8930980232

**Comment by epinter** [comment]
> @epinter if you are curious, built some c# bindings here and got a test console project to test stuff: https://github.com/Rem0o/ADLX/tree/main/Samples/csharp/ADLXWrapper.TestConsole

@Rem0o 
Off topic, but ... Don't you think the swig generated code is too much of a mess ? Looks like your need in fancontrol is only some sensors and fan settings... There are other ways where you implement only the part you will use, maybe it's  better than maintain the whole swig generated wrapper. I saw the wrapper, you have to use cpp too. I'm making some tests with ADLX, and I'm able to use it with pure c#, now I just able to get gpu name and VRAM, but the structure of the code seems to work. I was never a fan of generated code like that of swig.

**Comment by Rem0o** [comment]
@epinter  Well, not really. Actually I find it much easier to manage this way.  Most stuff in ADLX uses non-static method, so instance methods on IADLXInterface objects.   Without any wrapper, you would have to manage all the ptr handles to all these interface manually, still call acquire/release on them and so on.  

Swig allows me to have a class per type of instance automatically, auto-creates all the Extern/DLLImport code, manage all the c++ memory stuff, plus I can join some c++ code of my own to limit the unnecessary managed/unmanged transitions, most notably with IADLXGpuMetrics, where it requires 4 native calls in total to get all the metrics (gpu temp, memory temp, rpm) and I simplified it to only 1 call. 

Of course I end up using like 1/8 of the wrapper classes, but it's still 8 or 10 types of native class instance that are auto-generated for me and memory safe from the get go.  

The end result is the same, just less boiler plate that is easy to mess up.

**Comment by epinter** [comment]
> @epinter Well, not really. Actually I find it much easier to manage this way. Most stuff in ADLX uses non-static method, so instance methods on IADLXInterface objects. Without any wrapper, you would have to manage all the ptr handles to all these interface manually, still call acquire/release on them and so on.
> 
> Swig allows me to have a class per type of instance automatically, auto-creates all the Extern/DLLImport code, manage all the c++ memory stuff, plus I can join some c++ code of my own to limit the unnecessary managed/unmanged transitions, most notably with IADLXGpuMetrics, where it requires 4 native calls in total to get all the metrics (gpu temp, memory temp, rpm) and I simplified it to only 1 call.
> 
> Of course I end up using like 1/8 of the wrapper classes, but it's still 8 or 10 types of native class instance that are auto-generated for me and memory safe from the get go.
> 
> The end result is the same, just less boiler plate that is easy to mess up.

If you are already using c++, wouldn't be easier to write a small wrapper in c++ to return just what you need through static methods ?

**Comment by Rem0o** [comment]
> If you are already using c++, wouldn't be easier to write a small wrapper in c++ to return just what you need through static methods to c# ? A bridge, maybe using cli/c++.

That's what I'm doing for some stuff, but not for everything.  Still need to get the handles for every type of interface you need, and those are effectively instances, so they are easier to manage as such with the generated swig types.

**Comment by iDumle** [comment]
@epinter 
> @iDumle I know you must be tired of all the tests you made :) , I thank you really, unfortunatelly I don't see other developer working on the amd sensors on LHM, and I'm unable to reproduce... I really want to solve this thing, at least find the real cause. If you have a time, when you see your fans completely crazy try to run LHM and save the report (in the file menu).

I don't mind :), I'm enrolled in an IoT education, so doing issues and bug testing of each others projects is something I am familiar with, though I mostly work with python and some C on embedded systems, microcontrollers, SOC and such.
And I'm happy to try and help because I think it's an awesome software, and I do hope we can get the issues squashed so we can keep enjoying this great software.

> New build available:
> 
> https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/8930980232

But to the Issue at hand, I got all kinds of broken sensors in FanControl v188 today, so I ran the new LHM you linked and it's also showing a frozen core sensor though without as many "phantom" sensors.

Fancontrol looked like this.
![FanControl188Menu](https://github.com/Rem0o/FanControl.Releases/assets/141327899/b4b08711-fe8e-4756-b404-31eb6e46ab59)

And here is what LHM looked like.
![LHMBuildFromGithub-04-05-2024](https://github.com/Rem0o/FanControl.Releases/assets/141327899/3f8992fe-ead7-4640-b638-8e05767a2730)

And the report is here.
[LibreHardwareMonitor04-05-2024.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/15210633/LibreHardwareMonitor04-05-2024.Report.txt)

One thing I've noted is that the Max value seems to be updating correctly, It's just the live update that is broken. 
Here is a screenshot with me running apex in background.
![LHMBuildFromGithubPlayingApex-04-05-2024](https://github.com/Rem0o/FanControl.Releases/assets/141327899/38f0b878-eebb-48f4-9c7b-e4cfc91f0c54)
Don't know if a new report is necessary, but here is one from this screenshot.
[LibreHardwareMonitor04-05-2024WithApex.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/15210670/LibreHardwareMonitor04-05-2024WithApex.Report.txt)

**Comment by epinter** [comment]
> @epinter
> 
> > @iDumle I know you must be tired of all the tests you made :) , I thank you really, unfortunatelly I don't see other developer working on the amd sensors on LHM, and I'm unable to reproduce... I really want to solve this thing, at least find the real cause. If you have a time, when you see your fans completely crazy try to run LHM and save the report (in the file menu).
> 
> I don't mind :), I'm enrolled in an IoT education, so doing issues and bug testing of each others projects is something I am familiar with, though I mostly work with python and some C on embedded systems, microcontrollers, SOC and such. And I'm happy to try and help because I think it's an awesome software, and I do hope we can get the issues squashed so we can keep enjoying this great software.
> 
> > New build available:
> > https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/8930980232
> 
> But to the Issue at hand, I got all kinds of broken sensors in FanControl v188 today, so I ran the new LHM you linked and it's also showing a frozen Core and Hot spot sensor though without as many "phantom" sensors.
> 
> Fancontrol looked like this. ![FanControl188Menu](https://private-user-images.githubusercontent.com/141327899/327967373-b4b08711-fe8e-4756-b404-31eb6e46ab59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjU2MzAsIm5iZiI6MTcxNDg2NTMzMCwicGF0aCI6Ii8xNDEzMjc4OTkvMzI3OTY3MzczLWI0YjA4NzExLWZlOGUtNDc1Ni1iNDA0LTMxZWI2ZTQ2YWI1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMzI4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGQzZGI4NTNlNGU2OWUwOTE5YTAxMzFjMTI0Y2Y0MDVmM2U0OGIxNzIxODM2ZjJiYWMxNGNkNTQ0ZTg0NDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GurJ7l2BJqQACKs72ahJVY3EdteQwlJdADtIA7l-tQ)
> 
> And here is what LHM looked like. ![LHMBuildFromGithub-04-05-2024](https://private-user-images.githubusercontent.com/141327899/327967397-3f8992fe-ead7-4640-b638-8e05767a2730.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjU2MzAsIm5iZiI6MTcxNDg2NTMzMCwicGF0aCI6Ii8xNDEzMjc4OTkvMzI3OTY3Mzk3LTNmODk5MmZlLWVhZDctNDY0MC1iNjM4LThlMDU3NjdhMjczMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMzI4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGJmMjcxN2IzNDU5NDgxMmU3MmZiMzViYmM3NmMyMzExMWRmODgwY2M0OWMzNmE0NDZkZTdhYzA0NzU1ZGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1uNwBKJARpoxZfKVouHaYiFbyPKbIS_fZeURgUycgoI)
> 
> And the report is here. [LibreHardwareMonitor04-05-2024.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/15210633/LibreHardwareMonitor04-05-2024.Report.txt)
> 
> One thing I've noted is that the Max value seems to be updating correctly, It's just the live update that is broken. Here is a screenshot with me running apex in background. ![LHMBuildFromGithubPlayingApex-04-05-2024](https://private-user-images.githubusercontent.com/141327899/327968802-38f0b878-eebb-48f4-9c7b-e4cfc91f0c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjU2MzAsIm5iZiI6MTcxNDg2NTMzMCwicGF0aCI6Ii8xNDEzMjc4OTkvMzI3OTY4ODAyLTM4ZjBiODc4LWVlYmItNDhmNC05YzdiLWU0Y2ZjOTFmMGM1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMzI4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGY4NjZmNDM3NGY3Y2Y3Y2E0ZDQ1MDZlZjM3NDNiZDU4MjZlNWZhMDVhNjhkZTEwNWY4NGRhZmYyY2NlOTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vISab-2A0naAYCtLsPVSRtGwinAgw4dBten1q77S_9w) Don't know if a new report is necessary, but here is one from this screenshot. [LibreHardwareMonitor04-05-2024WithApex.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/15210670/LibreHardwareMonitor04-05-2024WithApex.Report.txt)

Embedded systems are nice to work with :)
Now, the report explains the issue, and it's weird, very weird:

Part of your report:
```
 Sensor[ADL_PMLOG_CLK_GFXCLK].Value: 192
 Sensor[ADL_PMLOG_CLK_GFXCLK].Value: 2
 Sensor[ADL_PMLOG_CLK_GFXCLK].Value: 4
 Sensor[ADL_PMLOG_CLK_GFXCLK].Value: 16842753
 Sensor[ADL_PMLOG_CLK_GFXCLK].Supported: True
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 2178
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 32762
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 3
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 1
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 4
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 7
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 17
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 20
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 21
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 37
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 19
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 12
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 14
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 13
 Sensor[ADL_PMLOG_CLK_MEMCLK].Supported: True
```

My report:
```
 Sensor[ADL_PMLOG_CLK_GFXCLK].Value: 16
 Sensor[ADL_PMLOG_CLK_GFXCLK].Supported: True
 Sensor[ADL_PMLOG_CLK_MEMCLK].Value: 30
 Sensor[ADL_PMLOG_CLK_MEMCLK].Supported: True
```

**Comment by epinter** [comment]
Here you go:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/8954072132

**Comment by epinter** [comment]
[net472-20240504-mt.zip](https://github.com/Rem0o/FanControl.Releases/files/15211308/net472-20240504-mt.zip)
Try this also, please.

**Comment by iDumle** [comment]
@epinter 
I have good news, both of these seems to work! 
I'm still on the same boot session with the broken sensors in the old version and the new ones are working as intended.

Here is screenshot from the first one.
![LHMBuildFromGithub8954072132-05-05-2024](https://github.com/Rem0o/FanControl.Releases/assets/141327899/d80a31c8-d418-4c77-af9d-94360a799f2d)

And here is the one you prefer.
![LHMBuildFromGithub20240504-mt-05-05-2024](https://github.com/Rem0o/FanControl.Releases/assets/141327899/c546a051-1620-4c7b-a0be-e98b50a74770)

Hopefully that mean the issue is resolved :)

**Comment by epinter** [comment]
Nice! I will update the commit and send you the build again from the LHM github for test, just in case...

**Comment by epinter** [comment]
Here, this build should work too.
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/8954631686

**Comment by iDumle** [comment]
> Here, this build should work too. https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/8954631686

Can confirm this one works too.
![LHMBuildFromGithub8954631686-05-05-2024](https://github.com/Rem0o/FanControl.Releases/assets/141327899/2698b853-f515-41ad-934d-1a658bb86a6c)

**Comment by epinter** [comment]
@iDumle 
Thank you very much for all your help! Now I believe the problem was solved, I think soon the commit will be merged.

**Comment by iDumle** [comment]
> @iDumle Thank you very much for all your help! Now I believe the problem was solved, I think soon the commit will be merged.

You're welcome I'm happy to help I do hope this will be it for this issue, and thank you for doing the work, your contribution enable us amd users to keep enjoying the software.

**Comment by Rem0o** [comment]
Latest LHMLib is in V189

**Comment by GEKonPC** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/162819753/27686859-03d7-4221-96fc-b318730b2c0d)
Hi sorry to disappoint but V189 is still broken :/

**Comment by epinter** [comment]
> Hi sorry to disappoint but V189 is still broken :/

@GEKonPC

I think this could be something in LHM yet. If you want to help, I can send you a build of LHM for you to collect the report. I see you have a RX 5700, we didn't test with series 5000 yet, maybe there's some adjust to make.

**Comment by GEKonPC** [comment]
Sure, send it but I will need instructions :D not as well versed in this as the other guy

**Comment by epinter** [comment]
> Sure, send it but I will need instructions :D not as well versed in this as the other guy
:)
Don't worry, do what you can, it's nothing complex... Unzip, run LibreHardMonitor.exe, go to menu File, click Save Report. Then just drag and drop the txt file here.

![Screenshot 2024-05-12 133107](https://github.com/Rem0o/FanControl.Releases/assets/1561280/0c9fad34-62d3-4276-97e5-ea4fc4e9141e)

**Comment by ouyangyiluo** [comment]
> 最新的 LHMLib 为 V189



> Latest LHMLib is in V189

![2024-05-13 034151](https://github.com/Rem0o/FanControl.Releases/assets/51234993/399296dd-4756-4b9d-a3b5-a6bf6cd76a2a)

**Comment by GEKonPC** [comment]
[WhenItsNOTWorking.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/15290467/WhenItsNOTWorking.Report.txt)
[WhenItsWorking.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/15290468/WhenItsWorking.Report.txt)
so i got 2 reports.. one where it was working and one where fan control failed to find 2 sensors and is reporting bonkers numbers again but looking at the LHM there it is reporting fine
![image](https://github.com/Rem0o/FanControl.Releases/assets/162819753/88ddd26d-e795-4974-be31-8214e10b6f89)

**Comment by epinter** [comment]
> so i got 2 reports.. one where it was working and one where fan control failed to find 2 sensors and is reporting bonkers numbers again but looking at the LHM there it is reporting fine

Great, thanks for the reports. Everything looks ok on both reports, the sensors found are consistent, also the data in each of the sensors. I don't see problem in LHM, let's way @Rem0o update FanControl.

**Comment by Rem0o** [comment]
@epinter 

FanControl V189 uses the latest commit  
 of LHM : https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/e62443761be5109538815c2e5dfb67e5333b3eab

**Comment by epinter** [comment]
> @epinter
> 
> FanControl V189 uses the latest commit of LHM : [LibreHardwareMonitor/LibreHardwareMonitor@e624437](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/e62443761be5109538815c2e5dfb67e5333b3eab)

md5 of V188 and V189 are the same:
```
 md5sum *net_4_8/LibreHardwareMonitorLib.dll *net_8_0/LibreHardwareMonitorLib.dll
0e9ac2177593b17589ec567509d422a3  FanControl_188_net_4_8/LibreHardwareMonitorLib.dll
0e9ac2177593b17589ec567509d422a3  FanControl_189_net_4_8/LibreHardwareMonitorLib.dll
e4ec0737857d4c66935f9033890ae907  FanControl_188_net_8_0/LibreHardwareMonitorLib.dll
e4ec0737857d4c66935f9033890ae907  FanControl_189_net_8_0/LibreHardwareMonitorLib.dll
```

**Comment by iDumle** [comment]
@Rem0o @epinter 
Can confirm that LHM in FanControl is broken, was just about to make a post about it because my FanControl was at 0 temp when I started my computer just now, I then tried to swap the DLL in to LHM to see if it would show the same, and it showed it was broken, where as the last version that epinter send me was working fine.

Here is Fan Control menu.
![FanControlMenu13-05-2024](https://github.com/Rem0o/FanControl.Releases/assets/141327899/18199764-d385-482a-a9ae-7a40073672de)

Here is the LHM that epinter send me last.
![LHMLastFixedVersionFromGit13-05-2024](https://github.com/Rem0o/FanControl.Releases/assets/141327899/625b7418-5a0d-4a85-8d19-66fd3c438648)

And here is the LHM running the DLL from fancontrol
![LHMFanControlDLL13-05-2024](https://github.com/Rem0o/FanControl.Releases/assets/141327899/dd2a5f0f-accc-48d8-9b09-4fe323afaeba)

**Comment by Rem0o** [comment]
Checked the hashes and I'm confused as to what's going on.
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/71bf482e-92aa-4288-a2ee-d9f318549885)

Will figure out what's going on.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V190

**Comment by User999999991** [comment]
V190 lost my GPU sensors.  Swapping in LHM files from V189 fixed it.

**Comment by epinter** [comment]
> V190 lost my GPU sensors. Swapping in LHM files from V189 fixed it.

What gpu you have ? Users tested AMD RX series 5000, 6000 and 7000, all of them worked as far as I know.

Test the latest nightly build of LHM: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/8958653644/artifacts/1474376834

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/issues/2509?notification_referrer_id=NT_kwDOANdwLLQxMDY1ODI5NDAxNzoxNDExODk1Ng

**Comment by epinter** [comment]
> @epinter
> 
> Seems like RX 400 and 500 series.
> 
> #2509

@Rem0o 
I think this cards might not work with PMLog. If it's the case, it's easy to exclude them and make them use old sensors. This would be a good test for ADLX too.

**Comment by User999999991** [comment]
My card is an AMD R9 280x.  Adding that latest LHM to Fan Control had the same problem as v190.  Got the same could not find expected sensors error again. The ADLX plugin didn't help either.

**Comment by epinter** [comment]
> My card is an AMD R9 280x. Adding that latest LHM to Fan Control had the same problem as v190. Got the same could not find expected sensors error again. The ADLX plugin didn't help either.

Must be the same problem of RX 400 and RX 500 series. Try this build of LHM, tell me if it works. Download links at the end of the page, LibreHardwareMonitor-net472 is full LHM, others are the libraries for other .net versions. 

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/9085676231

**Comment by User999999991** [comment]
> Must be the same problem of RX 400 and RX 500 series. Try this build of LHM, tell me if it works. Download links at the end of the page, LibreHardwareMonitor-net472 is full LHM, others are the libraries for other .net versions.
> 
> https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/9085676231

That LHM works again!

**Comment by epinter** [comment]
> > Must be the same problem of RX 400 and RX 500 series. Try this build of LHM, tell me if it works. Download links at the end of the page, LibreHardwareMonitor-net472 is full LHM, others are the libraries for other .net versions.
> > https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/9085676231
> 
> That LHM works again!

Nice , good to hear that!

**Comment by Rem0o** [comment]
[V191](https://github.com/Rem0o/FanControl.Releases/releases/tag/V191)  includes the changes made by @epinter to LHM.

**Comment by iDumle** [comment]
As far as I'm considered my issue has been resolved with v190, and if the new ones in this issue have made their own, I will close this.
Thanks for all the work. :)
