### ISSUE TITLE
Update from V24x to V247 leads to continous USB mass storage unmount/remount

### ISSUE THREAD

**Issue by Hymenochirus32** [Rem0o/FanControl.Releases#3697]
Like the title says, since I updated from an earlier version (V245 or V246 I guess), the startup of FanControl causes unmount and remount of one USB mass storage device (Chieftec internal card reader) every some seconds. As soon as FanControl is closes, the device works normally again.

This is NOT uniquely connected to FanControl, I had the same issue with WD Dashboard (now Sandisk Dashboard). But maybe they are using similar libraries. I would highly appreciate finding out what excactly causes this, it seems to have been integrated/changed in FanControl in the latest version.

Thanks!

**Comment by Blacktempel** [comment]
This seems weird.
Does this also happen when you use CrystalDiskInfo ?

Please provide "Log.txt" which is being created by "ConsoleOutputTest" in latest release from here:
https://github.com/Blacktempel/DiskInfoToolkit/releases

**Comment by Hymenochirus32** [comment]
> Does this also happen when you use CrystalDiskInfo ?

No.

> Please provide "Log.txt" which is being created by "ConsoleOutputTest" in latest release from here: https://github.com/Blacktempel/DiskInfoToolkit/releases

While executing the console tool, it happened also. [Log.txt](https://github.com/user-attachments/files/23568328/Log.txt)

**Comment by Blacktempel** [comment]
Thank you for the log. I will check it and see what I can do.

**Comment by Blacktempel** [comment]
That is a bit weird.
There is not a single drive letter in the log, yet it said device with drive letter 'S' was removed.
Was the log modified ?

**Comment by Hymenochirus32** [comment]
No, the log was not changed. The HDD and the two SSD cannot have just one drive letter, because they have multiple partitions. The card reader has multiple drives (one for each slot), but because I am only using the SD slot only one of them has a drive letter ('S').

**Comment by Blacktempel** [comment]
All partitions of all drives are also in the log file and usually contain the drive letter, if one was set for the partition.
Just weird that no partition seems to have one in the log, that's a first.

I will try to get a test version ready.

**Comment by Blacktempel** [comment]
I may have found a solution. This seems to work fine for my card reader devices.
Please try this, upload the log file and let me know if it solves your problem.

https://drive.google.com/file/d/1Wp96bqJQ6tQhXDj7xh-GM-KYX1PDQrfg/view?usp=sharing

```
OpenHashTab

20251117_1420_GithubTest_FC_3697_Debug.7z	MD5	95D6476700B8D95B56620A0695307254
20251117_1420_GithubTest_FC_3697_Debug.7z	SHA-1	F4769F7FB26E783744734E75A3576F665CE7889C
20251117_1420_GithubTest_FC_3697_Debug.7z	SHA-256	3A6721509B1180E38A2A99466C83CF8709A9F29123DE42234002B2A0D0DB502F
20251117_1420_GithubTest_FC_3697_Debug.7z	SHA-512	A12D0F47609EA0AE0ABF5F6FFDC6C916A327B59456137DF0675A93C8E2043139C11E02C4510864DD588846B7CD21A6F2B426F115C6C93788BDEFF58CDACB8D24
20251117_1420_GithubTest_FC_3697_Debug.7z	SHA3-512	A8B7AF103279A2B1B74299B0520C3D1165A87C22A41AB8FE2320E8881645AAF3B3CB31A498A6180966C4DE0F5A323213CBA2D396AD6E818182BB4A54C35A754B
```

**Comment by Hymenochirus32** [comment]
Thanks for your effort! Here you are: [Log.txt](https://github.com/user-attachments/files/23592052/Log.txt)

**Comment by MrMcFlyy** [comment]
Same problem for me (and my card reader), i reverted to v243. That seems to work.

**Comment by Blacktempel** [comment]
@MrMcFlyy 
Please upload a log file from most recent release here:
https://github.com/Blacktempel/DiskInfoToolkit/releases/tag/1.0.6

and from that specific version:

> I may have found a solution. This seems to work fine for my card reader devices. Please try this, upload the log file and let me know if it solves your problem.
> 
> https://drive.google.com/file/d/1Wp96bqJQ6tQhXDj7xh-GM-KYX1PDQrfg/view?usp=sharing
> 
> ```
> OpenHashTab
> 
> 20251117_1420_GithubTest_FC_3697_Debug.7z	MD5	95D6476700B8D95B56620A0695307254
> 20251117_1420_GithubTest_FC_3697_Debug.7z	SHA-1	F4769F7FB26E783744734E75A3576F665CE7889C
> 20251117_1420_GithubTest_FC_3697_Debug.7z	SHA-256	3A6721509B1180E38A2A99466C83CF8709A9F29123DE42234002B2A0D0DB502F
> 20251117_1420_GithubTest_FC_3697_Debug.7z	SHA-512	A12D0F47609EA0AE0ABF5F6FFDC6C916A327B59456137DF0675A93C8E2043139C11E02C4510864DD588846B7CD21A6F2B426F115C6C93788BDEFF58CDACB8D24
> 20251117_1420_GithubTest_FC_3697_Debug.7z	SHA3-512	A8B7AF103279A2B1B74299B0520C3D1165A87C22A41AB8FE2320E8881645AAF3B3CB31A498A6180966C4DE0F5A323213CBA2D396AD6E818182BB4A54C35A754B
> ```

**Comment by cdegut** [comment]
I have the same issue with 
(https://github.com/Blacktempel/DiskInfoToolkit/releases/tag/1.0.6)
but 
https://drive.google.com/file/d/1Wp96bqJQ6tQhXDj7xh-GM-KYX1PDQrfg/view?usp=sharing
Seem to work with no problem.

[Debug-Log.txt](https://github.com/user-attachments/files/23673674/Debug-Log.txt)

[1.0.6-Log.txt](https://github.com/user-attachments/files/23673677/1.0.6-Log.txt)

**Comment by altae7** [comment]
I've got the same issue with any version higher than 247. It keeps connecting and disconnecting USB devices forever. I've also got a card reader that is recognized as multiple USB devices. Actually version 247 is affected too but contrary to later versions the connect/ disconnect loop stops at some point. I've tried versions up to 250. Let me know if I can do something to help troubleshoot the issue.

**Comment by Blacktempel** [comment]
@altae7 
Please upload a log file from most recent release here (by running "ConsoleOutputTest"):
https://github.com/Blacktempel/DiskInfoToolkit/releases/

Also check if it still keeps happening as some edge cases were fixed.

**Comment by altae7** [comment]
Here is the requested log file. I ran ConsoleOutputTest.exe while version 250 was installed.

[Log.txt](https://github.com/user-attachments/files/23821469/Log.txt)

**Comment by Blacktempel** [comment]
Does it still happen with that version ?
I cannot see an issue in your log.

**Comment by altae7** [comment]
Yes it still happens with Version 250. In fact it's worse than version 247. When running version 247 the USB connect/ disconnect loop eventually stops and Fan Control runs without issues. With version 250 the loop never stops and Fan Control eventually crashes.

**Comment by Blacktempel** [comment]
Ah no, I was talking about the version of DiskInfoToolkit.
Does the issue still happen when executing ConsoleOutputTest or DiskInfoViewer ?
Please check this. That includes some fixes as mentioned.

**Comment by altae7** [comment]
OK, now it's clear. I can run both without getting into a USB connect/ disconnect loop.

**Comment by YukinoRikka** [comment]
I encountered the same problem, which persists in version v251. Even with the sensor temperature acquisition interval set, the USB mass storage device still disconnects. A temporary workaround is to uncheck the "Storage" option in the "Sensor Settings".

我也遇到了同样的问题，这个问题在 v251 版本中仍然存在。即使设置了传感器温度采集间隔，USB 大容量存储设备仍然会断开连接。一个临时的解决方法是在“传感器设置”中取消勾选“存储”选项。

**Comment by Blacktempel** [comment]
@YukinoRikka 
Please check this:
> Does the issue still happen when executing ConsoleOutputTest or DiskInfoViewer ? Please check this. That includes some fixes as mentioned.

And provide a log from ConsoleOutputTest.
Take latest release from here: https://github.com/Blacktempel/DiskInfoToolkit/releases

**Comment by YukinoRikka** [comment]
@Blacktempel 
I tested two USB devices, Lexar and Netac: When running ConsoleOutputTest, the Lexar worked fine, but the Netac disconnected.

Lexar log (working fine): [Log-lexar.txt](https://github.com/user-attachments/files/24028027/Log-lexar.txt)
Netac log (error occurred): [Log-netac.txt](https://github.com/user-attachments/files/24028034/Log-netac.txt)

**Comment by Hymenochirus32** [comment]
Having kept an eralier version, I now tried to update to V259, but directly at startup, my USB device is unmounted and after that an "unexpected error" shows up, Fan Control closes. Log.txt:

> [V259] 13.02.2026 22:34:36: Startup - System.ArgumentException: An item with the same key has already been added. Key: Time/
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.SpanToDictionary[TSource,TKey,TElement](ReadOnlySpan`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at FanControl.Domain.Utilities.CustomSensorOrdering.OrderBySensorDependencies(IEnumerable`1 sensorConfigs)
   at FanControl.Domain.Engine.FanControlEngine.DeserializeCustomSensors(IReadOnlyCollection`1 state)
   at FanControl.Domain.Engine.FanControlEngine.Restore(SerializableFanControlConfig config)
   at FanControl.Domain.ApplicationState.<>c__DisplayClass29_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.Engine.FanControlEngine.InitializeSensors()
   at FanControl.Bootstrap.Startup(StartupEventArgs eventArgs)
[V259] 13.02.2026 22:34:38: Dispose - System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.MainWindowViewModel.Dispose()
   at Autofac.Core.Disposer.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Container.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at FanControl.Bootstrap.Dispose()

**Comment by Rem0o** [comment]
@Hymenochirus32  send in your json config file.

**Comment by Hymenochirus32** [comment]
After downgrade to V245, my config was not loadable any more (just without any dialog about this). Obviously the updated version somehow had crashed the file. Luckily I could get back a working one from the backup folder.

[PC 2025-05.json](https://github.com/user-attachments/files/25314195/PC.2025-05.json)
[PC 2026-02.json](https://github.com/user-attachments/files/25314194/PC.2026-02.json)

But still there is the unmount problem in V259...

**Comment by MrMcFlyy** [comment]
Still same for me, i updated to the newest version and had the same problem with unmounting again. So downgraded to .243 which works fine.

[Normal.json](https://github.com/user-attachments/files/25314982/Normal.json)

**Comment by MrMcFlyy** [comment]
This is in my error log:

> [V260] 17.02.2026 21:22:21: LHM detected new sensors and asked for a refresh: /nvme/3/temperature/0
> /nvme/3/temperature/10
> /nvme/3/temperature/11
> /nvme/3/factor/23
> /nvme/3/factor/24
> /nvme/3/load/30
> /nvme/3/data/31
> /nvme/3/data/32
> /nvme/3/load/51
> /nvme/3/load/52
> /nvme/3/load/53
> /nvme/3/throughput/54
> /nvme/3/throughput/55
> [V260] 17.02.2026 21:22:37: LHM detected new sensors and asked for a refresh: /nvme/3/temperature/0
> /nvme/3/temperature/10
> /nvme/3/temperature/11
> /nvme/3/factor/23
> /nvme/3/factor/24
> /nvme/3/load/30
> /nvme/3/data/31
> /nvme/3/data/32
> /nvme/3/load/51
> /nvme/3/load/52
> /nvme/3/load/53
> /nvme/3/throughput/54
> /nvme/3/throughput/55
> [V260] 17.02.2026 21:23:17: LHM detected new sensors and asked for a refresh: /nvme/3/temperature/0
> /nvme/3/temperature/10
> /nvme/3/temperature/11
> /nvme/3/factor/23
> /nvme/3/factor/24
> /nvme/3/load/30
> /nvme/3/data/31
> /nvme/3/data/32
> /nvme/3/load/51
> /nvme/3/load/52
> /nvme/3/load/53
> /nvme/3/throughput/54
> /nvme/3/throughput/55
> [V260] 17.02.2026 21:23:34: LHM detected new sensors and asked for a refresh: /nvme/3/temperature/0
> /nvme/3/temperature/10
> /nvme/3/temperature/11
> /nvme/3/factor/23
> /nvme/3/factor/24
> /nvme/3/load/30
> /nvme/3/data/31
> /nvme/3/data/32
> /nvme/3/load/51
> /nvme/3/load/52
> /nvme/3/load/53
> /nvme/3/throughput/54
> /nvme/3/throughput/55

**Comment by MrMcFlyy** [comment]
I possibly solved it myself.

<img width="695" height="512" alt="Image" src="https://github.com/user-attachments/assets/aea28009-ab7a-4a68-ab98-bcbc1bf39579" />

I disabled all sensors i don't use in my source settings. Especially storage might have been a problem.

Now it works for some hours without a problem or disconnecting a USB-device.

Now only the question remains why it happened for versions .247 upwards and was fine for earlier versions including .246!

EDIT: Yes, after enabling the storage sensor again, i get the crashes. After disabling, it works fine.

**Comment by Blacktempel** [comment]
It's clear its related to Storage sensors, but it's not clear what exactly happens to cause that.
Some SD card readers / docking stations with SD card slots seem to dislike specific requests to identify the hardware.
For some people it has been fixed while others still report an issue.
Best would be if you could **_precisely list the hardware which is causing the issue_** so this can be investigated further.

I'm not sure if it's related to some manufacturers skipping some things and therefore crashing the devices driver.
Could be something else entirely.

Also check if you can run ConsoleOutputTest AND DiskInfoViewer (maybe restart a couple of times after disks were loaded via button) without getting a disconnection.
From latest release here: https://github.com/Blacktempel/DiskInfoToolkit/releases

**Comment by Hymenochirus32** [comment]
My first card reader is branded by Chieftec and introduces itself as a generic card reader. The second card reader is integrated in my screen and manufactured by Realtek (VID 0BDA, PID 0307). Both of them are using Microsoft drivers. If I remember correctly, the second one had some re-mount issues before, but I did not connect them with Fan Control. Also, it happened only about once a minute, not constantly like with Fan Control V247 or newer. In my former llog files it does not appear because it is only mounted if a card is inserted (unlike the other one).

**Comment by Blacktempel** [comment]
Newer FanControl versions use DiskInfoToolkit (DIT) as Storage implementation in LHM was replaced by that a while ago.
It has introduced a lot more data, though some parts could still improve. There's just too much different hardware to include every edge case from zero on.

Unfortunately I will need the exact model, the brand is not enough.
If it's cheap enough I may consider buying the same model and test it myself.

I can change a bit in DIT and provide a test version for you to test. Maybe I can find a "simple" fix.
I also need to know if it happens in either ConsoleOutputTest or DiskInfoViewer as I believe there's a possibility you cannot simply replace the dll in FC folder to test if it now works.

Please let me know if you are able to assist with testing.

**Comment by Hymenochirus32** [comment]
I don't have the package any more, but it seems to be CRD-601-U3.

I did some tests with ConsoleOutputTest as well as DiskInfoViewer for you before, do the results that I posted here answer your question? If not, please provide me the test tools and some short note what I should do and I will gladly try to help.

**Comment by Blacktempel** [comment]
> I don't have the package any more, but it seems to be CRD-601-U3.

Thanks, I'll see what I can do.

> I did some tests with ConsoleOutputTest as well as DiskInfoViewer for you before, do the results that I posted here answer your question? If not, please provide me the test tools and some short note what I should do and I will gladly try to help.

Please test it with latest version as of now. The last post of you testing it was from November, which is quite outdated as there have been some new versions in between.

>Also check if you can run ConsoleOutputTest AND DiskInfoViewer (maybe restart a couple of times after disks were loaded via button) without getting a disconnection.
From latest release here: https://github.com/Blacktempel/DiskInfoToolkit/releases

**Comment by Hymenochirus32** [comment]
Ok, could you please just explain what and when I should restart?

**Comment by Blacktempel** [comment]
> Ok, could you please just explain what and when I should restart?

DiskInfoViewer which is included in the release.
Let it run for a bit (1-2 min) after you press the button to load all disks. Check if disconnect happens.
Restart application (maybe a couple of times) and check again.

**Comment by MrMcFlyy** [comment]
I get disconnects of my SD card-reader with ConsoleOutputTest and DiskInfoViewer. How can i get you the log?

**Comment by Blacktempel** [comment]
Please re-check with latest release: https://github.com/Blacktempel/DiskInfoToolkit/releases
More SD Card readers were excluded.

FanControl v261 should already reflect these changes.

**Comment by Hymenochirus32** [comment]
So far no USB un-/re-mounts with v1.1.3 with both card readers in DiskInfoToolkit & ConsoleOutputTest.
[Log.txt](https://github.com/user-attachments/files/25739240/Log.txt)

Also, Fan Control V261 starts without any problems.

Thank you a lot for your help and the improvement!

**Comment by Hymenochirus32** [comment]
Unfortunately, the problem persists: After some time without any issue, I left a card for about five minutes in my reader and suddenly the re-mounting started again until I closed Fan Control. After starting Fan Control again, it immediately happened until I removed the card. I'm using V262.

**Comment by Blacktempel** [comment]
It's only happening when a SD card is inserted, right ?

Can you upload a new log from DiskInfoToolkit with a SD card inserted ?

**Comment by Hymenochirus32** [comment]
Sorry for the late replay due to a business trip.

Yes, and only after the SD card having been inside the reader for some minutes. Removing the card pauses re-mounting, and a reboot of the computer stops it completely.

Today, I could spend some time at my computer and had one card inserted. After some minutes, re-mounting started until I closed Fan Control. Directly after that I ran DiskInfoToolkit & ConsoleOutputTest, both with some re-mounts:
[Log.txt](https://github.com/user-attachments/files/26148980/Log.txt)

**Comment by Blacktempel** [comment]
I'm currently working on some improvements.

To properly reproduce this issue I have ordered a Chieftec SD card reader and will test as soon as I've received it. That way I can also verify if the new changes are working as expected.

**Comment by Blacktempel** [comment]
@Hymenochirus32 

I have received the Chieftec card reader and even removed all added SD Card filters from DiskInfoToolkit but still cannot reproduce it.
I'll continue trying, maybe it takes longer than a few minutes as you have suggested.

---

Would you be able to test a new version of DiskInfoToolkit ? Let me know and I'll get one ready - may take a bit.

**Comment by Blacktempel** [comment]
@Hymenochirus32 
Please test this version:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/2244#issuecomment-4184711807
